# Generated by Django 4.2.2 on 2023-08-30 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id_competence', models.AutoField(primary_key=True, serialize=False)),
                ('competence', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id_exp', models.AutoField(primary_key=True, serialize=False)),
                ('intituler_d_poste', models.CharField(max_length=150)),
                ('type_d_emploi', models.CharField(max_length=50)),
                ('nom_entreprise', models.CharField(max_length=150)),
                ('lieu', models.CharField(max_length=150)),
                ('date_debut_exp', models.DateField()),
                ('date_fin_exp', models.DateField()),
                ('titre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id_formation', models.AutoField(primary_key=True, serialize=False)),
                ('ecole', models.CharField(max_length=150)),
                ('date_debut_for', models.DateField()),
                ('date_fin_for', models.DateField()),
                ('resultat_obtenu', models.CharField(max_length=50)),
                ('activite_association', models.CharField(max_length=150)),
                ('domaine_d_etude', models.CharField(max_length=50)),
                ('diplome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id_langue', models.AutoField(primary_key=True, serialize=False)),
                ('langage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id_offre', models.AutoField(primary_key=True, serialize=False)),
                ('nom_poste', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('date_limite', models.DateField()),
                ('reference_poste', models.CharField(max_length=50, unique=True)),
                ('heure_de_travail', models.CharField(max_length=50)),
                ('mission', models.TextField()),
                ('profil_requis', models.TextField()),
                ('nombre_poste', models.CharField(max_length=50)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id_projet', models.AutoField(primary_key=True, serialize=False)),
                ('intituler', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('cible', models.CharField(max_length=100)),
                ('objectif', models.CharField(max_length=100)),
                ('duree_reelle', models.CharField(max_length=100)),
                ('date_debut_p', models.DateField()),
                ('date_fin_p', models.DateField()),
                ('date_debut_r', models.DateField()),
                ('date_fin_r', models.DateField()),
                ('observation', models.TextField()),
                ('statuts', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé')], max_length=25)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Postulant',
            fields=[
                ('id_postulant', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=150)),
                ('date_de_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('code_postal', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('copie_diplome', models.FileField(blank=True, max_length=150, null=True, upload_to='copie_diplome')),
                ('date_d_postule', models.DateField(auto_now_add=True)),
                ('CV', models.FileField(blank=True, max_length=150, null=True, upload_to='cv')),
                ('LM', models.FileField(blank=True, max_length=150, null=True, upload_to='lm')),
                ('coll_id', models.CharField(blank=True, max_length=10, null=True)),
                ('collaborateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suivis.postulant')),
                ('competences', models.ManyToManyField(related_name='postulants', to='suivis.competence')),
                ('experiences', models.ManyToManyField(related_name='postulants', to='suivis.experience')),
                ('formations', models.ManyToManyField(related_name='postulants', to='suivis.formation')),
                ('id_offre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suivis.offre')),
                ('langues', models.ManyToManyField(related_name='postulants', to='suivis.langue')),
            ],
        ),
        migrations.AddField(
            model_name='offre',
            name='id_projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suivis.projet'),
        ),
        migrations.CreateModel(
            name='Evaluer',
            fields=[
                ('id_evaluation', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_postulant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suivis.postulant')),
                ('id_projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suivis.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=150)),
                ('date_de_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('code_postal', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('copie_diplome', models.FileField(blank=True, max_length=150, null=True, upload_to='copie_diplome')),
                ('date_d_postule', models.DateField(auto_now_add=True)),
                ('CV', models.FileField(blank=True, max_length=150, null=True, upload_to='cv')),
                ('LM', models.FileField(blank=True, max_length=150, null=True, upload_to='lm')),
                ('est_postulant', models.BooleanField(default=True)),
                ('competences', models.ManyToManyField(related_name='collaborateurs', to='suivis.competence')),
                ('experiences', models.ManyToManyField(related_name='collaborateurs', to='suivis.experience')),
                ('formations', models.ManyToManyField(related_name='collaborateurs', to='suivis.formation')),
                ('id_offre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suivis.offre')),
                ('langues', models.ManyToManyField(related_name='collaborateurs', to='suivis.langue')),
            ],
        ),
    ]
