# Generated by Django 4.2.2 on 2023-08-31 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulant',
            name='coll_id',
        ),
        migrations.AlterField(
            model_name='postulant',
            name='collaborateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suivis.postulant'),
        ),
    ]
