# Generated by Django 4.2.2 on 2023-08-31 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivis', '0002_remove_postulant_coll_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulant',
            name='coll_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='collaborateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suivis.postulant'),
        ),
    ]
