# Generated by Django 4.2.2 on 2023-08-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivis', '0003_postulant_coll_id_alter_postulant_collaborateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulant',
            name='coll_id',
        ),
        migrations.RemoveField(
            model_name='postulant',
            name='collaborateur',
        ),
        migrations.AddField(
            model_name='postulant',
            name='is_collaborateur',
            field=models.BooleanField(default=False),
        ),
    ]
