# Generated by Django 4.2.2 on 2023-08-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_alter_utilisateurs_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
